name: predict_777_pages

on:
  workflow_dispatch: {}
  schedule:
    - cron: "40 22 * * *"   # JST 07:40

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 lxml

      - name: Build outputs (dummy scrape -> CSV)
        run: |
          mkdir -p outputs
          python scrape_dummy.py

      - name: Make HTML table
        run: |
          mkdir -p public
          echo "<html><head><meta charset='utf-8'><title>predict_777</title></head><body>" > public/index.html
          echo "<h1>predict_777.csv (最新)</h1>" >> public/index.html
          echo "<table border=1 cellspacing=0 cellpadding=4>" >> public/index.html
          head -n1 outputs/predict_777.csv | awk -F, '{print "<tr>"; for(i=1;i<=NF;i++){print "<th>"$i"</th>"}; print "</tr>"}' >> public/index.html
          tail -n +2 outputs/predict_777.csv | awk -F, '{print "<tr>"; for(i=1;i<=NF;i++){print "<td>"$i"</td>"}; print "</tr>"}' >> public/index.html
          echo "</table></body></html>" >> public/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:        # ← ここがポイント
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
